export default {
  startTime: 'Tanggal event',
  duration: 'Durasi event',
  select: 'Pilih',
  selectDate: 'Pilih tanggal...',
  selectTime: 'Pilih waktu...',
  selectDuration: 'Pilih durasi...',
  reply: 'Balas',
  unknownErrorMessage: 'Aplikasi FOMO sedang mengalami gangguan. Coba beberapa saat lagi.',
  forbiddenErrorMessage: 'Anda tidak bisa mengakses konten ini',
  oneDeviceLoginErrorMessage: 'Anda hanya bisa membuka aplikasi ini di satu perangkat saja. Coba keluar dan daftar kembali',
  public: 'Publik',
  profile: 'Profil',
  back: 'Kembali',
  close: 'Tutup',
  cancel: 'Batal',
  publish: 'Post',
  newPost: 'Posting',
  enterEmail: 'Masukkan alamat email kerja anda',
  enterVerificationCode: 'Kode verifikasi terkirim. Cek inbox atau folder spam / junk email anda',
  checkSpam: 'Email anda bisa delay sekitar 5 menit',
  enterPassword: 'Masukkan password anda',
  optional: ' (optional)',
  enterUsername: 'Masukkan nama samaran anda',
  enterPortalCode: 'Masukkan kode portal anda yang anda dapatkan dari akun lama anda',
  confirmPassword: 'Konfirmasi password anda',
  usernameChange: 'Anda juga bisa mengganti username anda lagi nanti',
  continue: 'Lanjut',
  firstToPost: 'Sepi nih. Coba anda post sesuatu untuk memulai interaksi',
  firstToComment: 'Sepi nih. Coba anda komentar untuk memulai interaksi',
  emptyContentAlert: 'Konten anda kosong',
  emptyCommentAlert: 'Komen anda kosong',
  emptyTitleAlert: 'Judul anda kosong',
  titlePlaceholder: 'Tag perusahaan yang kamu ingin tanyakan dengan memakai @ untuk nge-summon karyawan sana',
  eventNamePlaceholder: 'Diskusi mengenai ...',
  contentPlaceholder: 'Punya pertanyaan ke company tertentu? coba tag mereka pakai @',
  eventDescriptionPlaceholder: 'Deskripsikan event anda',
  forgotYourPassword: 'Lupa password anda?',
  selectEventFeature: 'Pilih fitur event anda...',
  incorrectPassword: 'Password yang anda masukkan salah',
  passwordMismatch: 'Password tidak sama. Coba di cek kembali',
  usernameAlreadyTaken: ' sudah tidak bisa dipakai. Coba pilih nama yg lain',
  choice: 'pilihan',
  emptyPostContentWarning: 'Judul atau konten pos anda kosong',
  forceUpdateWarning: 'Update aplikasi anda untuk mendapatkan fitur terbaru',
  confirmDeleteHeaderFormat: 'Hapus %s',
  confirmDeleteBodyFormat: 'Apakah anda yakin ingin menghapus %s anda?',
  confirmQuitGuestHeader: 'Siap menjadi fomozen?',
  confirmQuitGuestWarning: 'Kami yakinkan anda sekali lagi bahwa email kantor anda hanya kami pakai untuk memverifikasi anda kalau anda berdomisili di kantor anda. Setelah tahap verifikasi, kami tidak bisa lagi mengidentifikasi siapa anda',
  confirmDeleteEventWarning: 'Apakah anda yakin ingin membatalkan event anda?',
  confirmFlagUserWarning: 'Apakah anda yakin ingin melaporkan user ini?',
  confirmBlockUserWarning: 'Semua konten dari user ini tidak akan ditampilkan lagi. Apakah anda yakin ingin memblokir user ini?',
  flagContent: 'Laporkan konten',
  blockUser: 'Blok user',
  thankYouForFlagging: 'Terima kasih sudah membantu membangun komunitas ini menjadi komunitas yang berkualitas. Kami akan menginvestigasi dan menindaklanjuti laporan anda',
  addCommentPlaceholder: 'Tambah komentar...',
  edit: 'Edit',
  editTitle: 'Edit judul',
  editContent: 'Edit konten',
  editEvent: 'Edit event',
  delete: 'Hapus',
  save: 'Simpan',
  start: 'Mulai',
  username: 'Nama samaran',
  commentHasBeenDeleted: '(komentar telah dihapus)',
  userHasBeenBlocked: '(komentar user terblokir tidak ditampilkan)',
  newPostConfirmationWarning: 'Anda yakin mau mengunggah postingan ke ',
  newEventConfirmationWarning: 'Anda yakin mau membuat event baru di ',
  postTo: 'Posting ke ',
  privacyPolicy: 'Kebijakan Privasi',
  changeUsername: 'Ganti nama samaran',
  signOut: 'Log Out',
  giveFeedback: 'Beri Masukan',
  submit: 'Kirim',
  feedbackPlaceholder: 'Ada yang perlu diperbaiki atau bermasalah? Ayo laporkan segera ke tim kami',
  invalidVerificationCodeWarning: 'Kode yang anda masukan salah, silahkan coba kembali.',
  useYourWorkEmailWarning: 'Gunakanlah email kerja anda!',
  welcomeMessage: 'Selamat Datang',
  welcomeTopMessage: 'adalah sebuah forum anonim untuk ngobrol sesama profesional se-Indonesia. Kami sendiri pun tidak bisa mengidentifikasi siapa anda.',
  welcomeBottomMessage: 'Bahkan jika HR perusahaan anda ingin mencari tahu siapa anda, kami tidak bisa membantu mereka',
  enterEmailMessage: 'Email kantor hanya dipakai untuk verifikasi dan mengumpulkan anda dengan teman seperjuangan anda',
  thankYou: 'Terima kasih',
  thankYouForFeedbackMessage: 'Masukan anda membantu kami untuk menciptakan fomo sebagai tempat yang nyaman dan aman bagi komunitas fomo',
  mostRecent: 'Paling baru',
  mostViewed: 'Paling dilihat',
  mostCommented: 'Paling dikomentari',
  mostLiked: 'Paling disukai',
  trending: 'Trending',
  sortBy: 'Sortir berdasarkan',
  registeredCompanies: 'Institusi yang terdaftar (jumlah orang)',
  total: 'jumlah',
  inThisChannel: 'Institusi di channel ini (jumlah orang)',
  topic: 'Topik',
  views: 'melihat',
  likes: 'menyukai',
  comments: 'komentar',
  filter: 'Filter',
  clearFilter: 'Hapus filter',
  noPostFoundWithFilter: 'Belum ada postingan nih. Yuk bikin untuk memulai diskusi dengan fomozen lainnya',
  onceADayUsernameChangeWarning: 'Anda hanya bisa mengganti username anda sekali dalam 24 jam',
  emptyNotification: 'Tidak ada notifikasi',
  notifications: 'Notifikasi',
  thePost: 'postingan',
  theComment: 'komentar',
  activityHistory: 'Riwayat Aktivitas',
  noActivityFound: 'Anda belum pernah berinteraksi. Ayo jangan sampai ketinggalan dengan fomozen lainnya',
  createPostActivity: "Membuat postingan di ",
  commentOnPostActivity: "Mengomentari postingan di %s berjudul ",
  likeOnPostActivity: "Menyukai postingan di %s berjudul ",
  voteOnPostActivity: "Memvoting postingan di %s berjudul ",
  replyOnCommentActivity: "Membalas komentar postingan di %s berjudul ",
  likeOnCommentActivity: "Menyukai komentar postingan di %s berjudul ",
  joinAsGuest: 'Hanya punya email pribadi',
  areYouSure: 'Anda yakin?',
  join: 'Masuk',
  port: 'Pindahkan',
  register: 'Daftar',
  registerNow: 'Daftar sekarang',
  guestInteractionWarning: 'Tanpa registrasi email anda, fitur seperti like, komentar, DM, subforum, dan fitur lainnya tidak bisa digunakan',
  edited: 'diedit',
  agreeToTerms: 'Dengan mendaftar, anda setuju dengan aturan dan ketentuan yang telah ditentukan di https://fomo.id/PrivacyPolicy',
  feed: 'Home',
  search: 'Cari',
  searchPlaceholder: 'Cari postingan',
  imageSearchPlaceholder: 'Cari gambar',
  referralAlertTitle: 'Kode referal',
  referralAlertContent: 'Apakah anda punya kode referal dari teman anda yang memberi tahu anda tentang Fomo?',
  yes: 'Ya',
  no: 'Tidak',
  skip: 'Lewati',
  enterReferralCode: 'Masukkan kode referal',
  wrongReferralCode: 'Kode referal yang anda masukkan salah. Coba diperiksa kembali',
  noCodeReferral: 'Tidak punya kode',
  skipReferralAlertContent: 'Anda yakin ingin melewati tahap ini? Setelah mendaftar menjadi member Fomo, anda tidak bisa memasukkan kode referal dari teman anda lagi.',
  referralCodeConfirmation: 'Anda yakin dengan kode referral yang anda masukkan?',
  referralSuccessful: 'Terima kasih. Kode referral yang anda masukkan sudah kami terima',
  polling: 'Polling',
  optionPrefix: 'Opsi ',
  pollingNotReady: 'Polling belum siap',
  pollingReady: 'Polling siap',
  vote: 'Pilih',
  totalRespondence: 'Total responden',
  event: 'Event',
  channel: 'Subfomo',
  postHasBeenDeleted: "Postingan sudah dihapus",
  confirmSignOut: "STOP! HARAP DIBACA",
  confirmSignOutText: "Jika anda keluar tanpa menyimpan kode berikut ini, maka akun anda tidak akan bisa diakses lagi tanpa kode ini",
  copyCode: "Kopi kode",
  copyConfirm: "Kode sudah ada di clipboard anda. Pastikan bahwa anda menyimpan kode ini di tempat yang aman. Kode ini digunakan untuk memindahkan akun anda ke ponsel anda lainnya. Apabila anda mendaftar dengan email yang sama tanpa kode ini, akun anda akan kami anggap sebagai akun baru. SUDAH SIMPAN KODE ANDA?",
  codeSaved: "Sudah",
  portAccount: "Pindahkan akun saya ke ponsel ini",
  portalCodePlaceholder: "Kode portal",
  portAccountSuccessful: "Porting akun berhasil",
  welcomeBackTitleFormat: "'%s' · '%s'",
  failedToPortAccount: "Kode portal salah, coba dicek kembali",
  dontHavePortalCode: "Tidak mempunyai kode portal",
  image: "Gambar",
  noImageFound: "Tidak ada gambar yang memenuhi kriteria anda",
  inviteColleague: "Ajak Kolega Anda",
  inviteeEmailPlaceholderPrefix: 'temanmu@',
  inviteColleagueAlertTitle: 'Ajak kolega anda?',
  invite: "Ajak",
  inviteColleagueConfirmationWarning: "Kami akan mengirimkan email ke kolega anda atas nama 'fomo'. Identitas anda tidak akan diketahui sama sekali karena kami sendiri memang tidak memilikinya 😎",
  inviteAccepted: "Ajakan anda sudah kami terima. Ayo ajak kolega anda lainnya untuk semakin meramaikan fomo",
  lifetimePoints: "Lifetime points",
  availablePoints: "Redeemable points",
  commentedPost: "Komentar di postingan anda",
  votedPost: "Votingan di polling anda",
  likedComment: "Like di komentar anda",
  repliedComment: "Balasan di komentar anda",
  convertedInvitation: "Ajakan kolega yang terkonversi",
  additionPer: "Tambahan setiap",
  points: "Poin",
  reputation: "Reputasi anda",
  none: "Tidak punya",
  reputationThreshold: "Lifetime points",
  male: "L",
  female: "P",
  updateToLatest: 'Update aplikasi anda ke versi terbaru untuk menukarkan poin anda dengan barang menarik',
  stayTunedRedeemPoint: 'Fitur untuk menukarkan poin masih dalam pengerjaan. Tunggu tanggal mainnya yah 😎',
  startInteraction: 'Mulailah interaksi',
  chat: "Chat",
  inviteToChat: "Ajak ngobrol",
  writeAMessage: "Tulis pesan kamu...",
  askQuestion: "Apa yang kamu mau tahu...",
  follow: "Follow",
  following: "Following",
  comment: "Komentar",
  share: "Share",
  commentHasBeenFlagged: '(komentar telah diban)',
  noChats: "Ajak ngobrol fomozen favoritmu dengan mengklik tombol '3 dot' dibagian postingan atau komentar",
  help: 'Help',
  latest: 'terbaru',
  testProfile: "Tes profil",
  pleaseWait: "Mohon ditunggu",
  newCommentAvailable: "↻   Komentar baru",
  refreshPage: "↻   Refresh",
  loadOldChats: "↑  Chat lama",
  noEventFound: "Tidak ada event yang sedang berlangsung. Buat event sekarang juga",
  createEventIn: "Buat event di ",
  eventFeature: "Fitur event",
  createEvent: "Buat event",
  cancelEvent: "Batalkan event",
  eventPassed: "✔ PAST",
  eventCanceled: "✘ CANCELED",
  eventLive: "◉ LIVE",
  eventUpcoming: "↗ NEXT",
  POLL: "POLL",
  liveChat: "Live chat",
  hasEvent: "Event",
  hasPolling: "Polling",
  modifyEvent: "Ubah event",
  confirmModifyEventWarning: "Apakah anda yakin ingin mengubah event anda?",
  qAndA: 'Q & A',
  poll: "Poll",
  quiz: "Quiz",
  done: "Selesai",
  enterEventPassword: "Masukkan event password. Jika anda tidak mengetahuinya, tanya host dari event ini",
  enterPollTitle: "Apa yang mau anda tanyakan?",
  confirmAskAudience: "Yakin untuk menanyakan ini ke audience anda?",
  noPollsAvailable: "Belum ada poll yang dibuat oleh host event anda",
  publicLive: "Public Live Webinar",
  askAudience: "Tanya audience",
  eventLinkAlertHeader: "Desktop",
  eventLinkAlertBody: "Masukkan alamat dan kode dibawah ini ke browser desktop anda",
  eventLinkAlert2ndHeader: "Link sudah di clipboard anda",
  eventLinkAlert3rdHeader: "Kode sudah di clipboard anda",
  eventLinkAlert3rdBody: "Simpan baik-baik kode ini karena ini adalah kode identitas akun anda",
  eventLinkAlert2ndBody: "Untuk dark mode, anda tinggal mengganti dm=false menjadi dm=true di link anda",
  facebook: "Facebook",
  youtube: "Youtube",
  zoom: "Zoom",
  zoomMeeting: "Zoom meeting ID",
  hideVideo: "Hide Video",
  eventPassword: "Event password",
  showCode: "Copy Link",
  jobs: "Lowongan",
  noJobsFound: "Tidak ada jobs yang memenuhi kriteria filter anda",
  jobDescriptions: "Deskripsi Lowongan",
  jobQualifications: "Kualifikasi",
  jobBenefits: "Tunjangan",
  minimumSalary: "Minimum gaji",
  jobType: "Tipe pekerjaan",
  showAll: "Tampilkan semua",
  jobTitle: "Posisi",
  jobLocation: "Lokasi",
  applyJob: "Lamar",
  resume: "Curriculum Vitae",
  whyMove: "Apa alasan anda pindah?",
  whyMovePlaceholder: "Saya ingin berkembang lebih cepat...",
  whyYou: "Kenapa anda yang harus kami terima?",
  whyYouPlaceholder: "Saya merasa bisa berkontribusi...",
  whyThisCompany: "Kenapa perusahaan kami?",
  whyThisCompanyPlaceholder: "Perusahaan anda mempunyai banyak kesempatan untuk belajar...",
  uploaded: "Diterima ",
  upload: "Upload (max 1MB)",
  minYearsOfExperience: "Minimum pengalaman kerja",
  yourYearsOfExperience: "Pengalaman kerja anda",
  recentlyGraduated: "Baru lulus",
  years: " tahun",
  rangeSalary: "Range gaji",
  companyName: "Perusahaan",
  jobSource: "Job Source",
  beTheFirstToReview: "Belum ada review di perusahaan ini",
  writeReview: "My Review",
  careerGrowth: "Jenjang Karir",
  workLifeBalance: "Work/Life Balance",
  compensationAndBenefits: "Kompensasi/Tunjangan",
  companyCulture: "Kultur Perusahaan",
  managementAndLeadership: "Manajemen/Leadership",
  pros: "Pros",
  cons: "Cons",
  enterCompanyPro: "Enaknya kerja dikantor ini...",
  enterCompanyCon: "Ga enaknya kerja dikantor ini...",
  reviewTitle: "Judul review",
  reviewHighlight: "Sentimen kamu ke perusahaan ini...",
  experienceSharing: "Konten review",
  experienceSharingPlaceholder: "Sharing pengalaman kamu disini...",
  myReview: "Ulasan saya",
  companyRating: "Rating perusahaan",
  reviews: "Reviews",
  review: "Review",
  detail: "Detail",
  max60Chars: " (max 60 karakter)",
  max2000Chars: " (max 2000 karakter)",
  like: "Like",
  followers: "followers",
  sponsored: "Sponsored",
  readMore: "baca selengkapnya...",
  theCompanyReview: "review",
  postTitle: "Judul Posting",
  postContent: "Konten Posting",
  addOption: "Tambah opsi",
  eventActive: "Event aktif",
  noEvent: "Tidak ada event",
  addPro: "Tambah pro",
  addCon: "Tambah con",
  survey: "Survey",
  bookmarkedThreads: "Bookmarked Threads",
  noBookmarkedThreadsFound: "Belum ada thread yang anda bookmark",
  blockUserSuccessful: "User '%s' telah diblokir. Konten dari user tersebut tidak akan kami tampilkan lagi di halaman anda selambat-lambatnya 1 jam dari sekarang.",
  forum: 'Forum',
  copyMessage: "Pesan berhasil dicopy",
  createPost: "Buat Post",
  editPost: "Edit Post",
  createSubFomo: "Buat Subfomo",
  editSubFomo: "Edit Subfomo",
  subFomoNamePlaceholder: "Apa nama subfomo yang menarik?",
  subFomoDescriptionPlaceholder: "Berikan penjelasan dan aturan dari subfomo yang kamu buat",
  subFomoName: "Nama Subfomo",
  subDomoDesc: "Deskripsi",
  create: "Buat",
  subFomo: "Subfomo",
  insufficientPointMessageFormat: "Point anda kurang dari %s",
  duplicateData: "Data Sudah Ada",
  noSubfomo: "Belum ada subfomo silahkan buat atau ikuti subfomo publik",
  camera: "Camera",
  galeri: "Galeri",
  uploadPhoto: "Upload gambar berhasil",
  confirmMessageToCreateSubfomo: "Anda yakin untuk menggunakan 1000 poin untuk membuat channel ini?",
  sure: "Yakin",
  uploadImage: "Upload gambar",
  editChannel: "Edit channel",
  selectSubfomo: 'Pilih Subfomo',
  changeCompany: 'Pindah Perusahaan',
  move: 'Pindah',
  confirmMergeAccount: 'Jika anda pindah perusahaan, kami akan memindahkan poin yang sudah anda kumpulkan, kepemilikan subfomo anda, dan postingan yang sudah anda bookmark ke akun baru. DM dan riwayat aktifitas anda tidak dapat dipindahkan',
  company: "Company",
  replyingTo: 'Membalas "%s"',
  searchCompany: "Search company",
  searchJobTitle: "Cari posisi (ex: Software Engineer)",
  confirmJobTitle: "Apakah anda ingin mendaftarkan posisi '%s' ?",
  companyEmpty: "Tidak ada perusahaan yang memenuhi kriteria anda",
  createJobTitle: "Buat job title",
  seeOtherReviews: 'Lihat ulasan lain',
  yourCurrentOffice: "Kantormu saat ini",
  editComment: "Editing comment",
  unprocessableEntityMessage: "Pastikan teks yang ada masukkan valid.",
  badRequestMessage: "Coba cek kembali request yang anda kirim",
  subfomoAlreadyTaken: "Subfomo dengan nama ini sudah terpakai",
  badConnection: "Gagal memuat konten. Refresh atau periksa koneksi internet kamu",
  badConnectionTitle: "Terjadi Kesalahan",
  deleteAccount: 'Hapus akun',
  searchSubfomo: "Search subfomo",
  deletedAccount: "Akun terhapus",
  areYouSureDeleteAccount: "Anda akan menghapus akun",
  messageDeleteAccount: "Menghapus akun berarti anda akan kehilangan FomoPoints, bookmark, subfomo dan semua yang berhubungan dengan akun anda. Yakin akan menghapus?",
  messageDeleteAccountSuccess: "Request penghapusan akun telah kami terima. Akun anda akan terhapus selambat-lambatnya 48 jam kedepan. Anda masih dapat membatalkan penghapusan akun anda dengan login kembali menggunakan kode portal yang sudah di clipboard anda. Simpan kode portal anda jika anda berubah pikiran. %s",
  retry: "Muat ulang",
  tax: "Pajak FOMO",
  taxPlaceholder: "Pajak sesuai konteks pertanyaan di thread",
  taxDescription: "Pajak FOMO adalah norma tidak tertulis yang paling sakral di sini. Sederhananya, sebelum kamu menanyakan sesuatu, ada baiknya jika kamu memberi jawaban dari perspektif kamu. Misalkan:",
  taxExample: "\"Gaji recruiter di Netflix berapa? Pajak Fomo: di kantor gw 45juta/bulan nett\"",
  copyCodePortal: "Kode portal sudah tercopy di clipboard anda. Simpan kode portal Anda di notepad atau sejenisnya",
  inputSalary: "Post Gaji",
  roleLevel: "Role Level",
  roleLevelPlaceholder: "Grade 3, Senior, dll",
  yoe: "YoE",
  yoePlacehoder: "Year of Experience",
  thp: "Gaji bulanan",
  thpPlaceholder: "Gaji bersih/nett sebulan",
  annualBonus: "Bonus tahunan",
  annualBonusPlaceholder: "THR, saham, dll",
  allowance: "Allowance",
  allowancePlaceholder: "Tambahkan allowance",
  annualMarketPriceEquity: "Bonus Saham Tahunan",
  annualMarketPriceEquityPlaceholder: "Berdasarkan harga saham hari ini",
  addCompanyReview: "Tambah Review",
  addSalary: "Tambah Gaji",
  createRoleLevel: "Buat role level",
  searchRoleLevel: "Search role level",
  addSalarySucceed: "Tambah Gaji Berhasil",
  copyComment: "Text berhasil dicopy",
  editSalarySucceed: "Edit Gaji Berhasil",
  labelTabSalary: "Gaji",
  labelTabReview: "Ulasan",
  addNewSurvey: "Tambah Survey",
  addNewPost: "Tambah Postingan",
  createSurvey: "Buat Survey",
  editSurvey: "Edit Survey",
  surveyQuestionPlaceholder: "Tambahkan pertanyaan anda",
  salaryInputNumberInvalidErrorMessage: "Cek kembali angka yang ada masukkan",
  waitAMinute: "Tunggu dulu!",
  lockedMessageSubscriptionAndCutFomopoint: "Perlu %s fomopoint untuk ngintp %s. Atau kamu bisa coba subscribe FOMO+ buat buka semua fitur intip gaji dan ulasan kantor.",
  lockedMessageNonProfessionalUserFormat: "Butuh %s fomopoint buat melihat konten ini.",
  cutFomopoint: "Potong Fomopoint",
  tryPremium: "Coba premium",
  submitSalary: "Submit Gaji",
  submitReview: "Submit Review",
  submitSalaryData: "submit data gaji",
  reviewCompany: "review kantor",
  subfomoNotFound: "Subfomo tidak di temukan",
  thread: "Thread",
  setting: "Setting",
  postAPicture: "Post a Picture",
  postAPictureDescription: "Pengen upload gambar juga? Makanya langganan",
  upgradeAccount: "Silahkan subscribe fomo+ dulu",
  imageUploadErrorMessage: "Waduh... coba upload ulang, gan. Yang tadi gagal :(",
  blockUserOnChatSuccessful: "User '%s' telah diblokir dan user '%s' tidak bisa menghubungi anda lagi",
  mySalary: "Gaji saya",
  fomoPlus: "FOMO+",
  myProfile: "Profil Saya",
  invoice: "Invoice",
  subscribe: "langganan",
  subscribeFomoPlus: "Langganan FOMO+",
  activeUntil: "Aktif sampai",
  invoiceNotFound: "Kamu belum memiliki invoice, ayo berlangganan",
  copyInvoiceId: "Invoice ID berhasil dicopy",
  try: "Coba",
  companyReview: "Company Review",
  salary: "Gaji",
  open: "buka %s",
  validUntil: "Valid sampai",
  openWith: "Dibuka menggunakan",
  termsOfUse: "Terms Of Use",
  month: "bulan",
  supportFomo: "Support FOMO ah!",
  skipFomoPlus: "Skip dulu min",
  mod: "Mod",
  reportedContent: "Reported content",
  banList: "Ban List",
  reported: "Reported",
  deletedThreads: "Deleted Threads",
  reportContentTitleModal: "Laporkan orang ini atas pelanggaran apa?",
  action: "Action",
  shadowbanContentMessage: "Yakin melakukan shadowban konten ini?",
  alertMessageRecoverContent: "Yakin melakukan recover konten ini?",
  alertMessageUnbanUser: "Yakin mau unban user ini?",
  banUntil: "Ban selesai: ",
  unbanWasSuccessfulMessage: "User berhasil diunban",
  sendWarning: "Kirim warning",
  banDaysFormat: "Ban %s hari",
  unban: "Unban",
  unbanContentSuccessfulMessage: "Konten berhasil direcover",
  banContentSuccessfulMessage: "Konten berhasil diban",
  sendPunishmentSuccessfulMessage: "Sangsi sudah dikirim",
  lockedMessageSubscriptionAndSubmissionFormat: "Kamu mesti ngasih %s kamu dulu buat ngintip %s. Atau kamu bisa coba subscribe FOMO+ buat buka semua konten gaji beserta summarynya dan juga konten ulasan kantor.",
  messageIsRequiredInputReviewFormat: "(minimal 20 karakter)",
  skipRegister: "Skip Registrasi",
  searchGlobalPlaceholder: "Cari perusahaan atau posisi",
  submitReviewSuccessful: "Submit review sukses",
  messageCopyLink: "Link sudah di clipboard",
  baseUrl: "https://fomo.azurewebsites.net/",
  baseUrlStage: "https://fomo-stage.azurewebsites.net/",
  marketingConsentSectionTitle: "Persetujuan Fomozen",
  marketingConsentMessage: "Saya memberikan izin agar thread ini dapat didistribusikan keluar sebagai materi promosi",
  roleSalary: "Role Salary",
  imageUploadSizeError: "Gambar yang anda upload melebihi 5MB size limit, silahkan dicoba kembali",
  talentMarket: "Talentmarket",
  talentmarketLabel: "Thread di Talentmarket",
  showThread: "Lihat thread",
  createThread: "Buat thread",
  postTalentmarket: "Post Talentmarket",
  validateMessageEmptyRole: "Sebelum membuat thread di Talent Market, kamu harus mengisi data gaji kamu terlebih dahulu untuk mempermudah recruiter mendapatkan informasi yang mereka butuhkan.",
  validateMessageEmptyJobTitle: "Kami menemukan ada informasi di dalam data gaji kamu yang perlu dibenerin. Silakan masukkan data yang bener biar kamu bisa membuat postingan di Talent Market.",
  skipIt: "Skip dulu",
  youCan: "BOLEH TUH!",
  fomoJobs: "Jobs",
  messageUseProfesionalAccount: "Gunakan akun profesional",
  alertNonProfesionalAccountPostInPublic: "Yuk pindah akun profesional supaya bisa ngepost di publik",
  alertUserHasBannedFromSubfomo: "Ups, kamu sedang di ban di subfomo %s",
  postReview: "Post Review",
  youAlreadyPosted: "Karena kamu udah pernah ngepost %s, kamu bisa ngepost lagi tanggal %s ya. Atau kamu udah ga di logo? Pindah perusahaan dulu baru bikin ulasan baru",
  allOffices: "Semua kantor",
  messageTitlePostTooLong: "Judul posting terlalu panjang, gan",
  messageContentPostTooLong: "Konten kamu terlalu panjang, gan",
  myCareer: "Karir Saya",
  jobdesc: "Jobdesc",
  offering: "Offering",
  lowerBidLimit: "Jangan di bawah UMR gan",
  upperLimitOffers: "Jangan ketinggian juga gan",
  talentmarket: "Talentmarket",
  jobMarket: "Jobmarket",
  postJobmarket: "Post Jobmarket",
  alertNonProfesionalAccountPostFormat: "Yuk pindah akun profesional supaya bisa ngepost %s",
  youAlreadyPostedJob: "Kamu sudah punya %s yang aktif"
};
